- name: Upgrade all pip packages in a specified virtual environment
  hosts: localhost
  connection: local
  vars_prompt:
    - name: venv_directory
      prompt: "Enter the directory name of the virtual environment"
      private: false
  tasks:
    - name: Check if virtual environment exists
      ansible.builtin.stat:
        path: "/home/wil031583/virtual_environments/{{ venv_directory }}/bin/activate"
      register: venv_activate_script
    - name: Fail if virtual environment does not exist
      ansible.builtin.fail:
        msg: "The specified virtual environment does not exist."
      when: not venv_activate_script.stat.exists
    - name: Upgrade all pip packages
      ansible.builtin.shell: |
        set -o pipefail
        source /home/wil031583/virtual_environments/{{ venv_directory }}/bin/activate
        pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
      args:
        executable: /bin/bash
      register: pip_upgrade
      changed_when: "'Installing collected packages' in pip_upgrade.stdout"
      when: venv_activate_script.stat.exists
